type: prometheus
# Prometheus-compatible datasource — works with Prometheus, Mimir, Thanos, VictoriaMetrics (all use same API + PromQL)

global:
  clients:
    - name: default
      url: http://prometheus-prometheus-stack-kube-prom-prometheus-0.prometheus-operated:9090
      api: api/v1
      timeout: 30 #second

  range_configs:
    - name: default
      start_time: "1d"
      end_time: "now"
      step: "15s"
      start_end_slice: "5min"

  query_result_exports:
    - name: default
      export_metric:
        - name: "instance"
          override: ""

    - name: export_instance_as_job
      export_metric:
        - name: "instance"
          override: "job"

  output_configs:
    - name: default
      relative_path: ""
      print_output: false
      write_output:
        - type: csv
          dir: "result/csv"
        - type: json
          dir: "result/json"

    - name: print_only
      print_output: true
      write_output: []

queries:
  single:
    - name: "query_prometheus_health"
      promql: 'up{pod="prometheus-prometheus-stack-kube-prom-prometheus-0",container="prometheus"}'
      query_result_exports: "export_instance_as_job"
      output_configs: "print_only"

  range:
    - name: "query_node_memory_free"
      promql: "node_memory_MemFree_bytes"
